language: android
android:
    components:
        # Build tools version
        - build-tools-21.1.2

        # SDK version
        - android-21
        
        # Additional components
        - extra-android-m2repository

script: "./gradlew assembleDebug"

git:
    submodules: false

